# Women Cloth Reviews Prediction with Multi Nomial Naive Bayes

the multinomial Naive Bayes classifier is suitable for classification with discrete features(e.g., word counts for text classification).The multinomial distribution normally requires integer feature counts. However, in practice,fractional counts such as tf-idf may also work

## Import Library

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Import Dataset

In [5]:
df= pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Teaching-Data/main/Women%20Clothing%20E-Commerce%20Review.csv')

In [6]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [8]:
df.shape

(23486, 10)

## Missing Values

Remove missing values in Reviews colums with No Review test


In [9]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [12]:
df[df['Review']==""]=np.NaN

In [13]:
df['Review'].fillna("No Review",inplace=True)

In [14]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [15]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

Define Target (y) and Feature (X)

In [16]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [17]:
X=df['Review']
y=df['Rating']

In [18]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

## Train Test Split

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.7,random_state=2529)

In [21]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((7045,), (16441,), (7045,), (16441,))

## Get Feature Text Conversion to Tokens

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [27]:
X_train=cv.fit_transform(X_train)

In [29]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years come', 'yellow color',
       'yoga pants'], dtype=object)

In [30]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [31]:
X_test=cv.fit_transform(X_test)

In [32]:
cv.get_feature_names_out()

array(['00p 0p', '10 12', '10 bought', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [ ]:
X_test.toarray()

## Get Model Train

In [33]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

## Get Model Prediction

In [35]:
y_pred=model.predict(X_test)
y_pred.shape

(16441,)

In [37]:
y_pred

array([1, 5, 3, ..., 1, 2, 1])

## Get Probablity of Each Predicted Class

In [38]:
model.predict_proba(X_test)

array([[0.39409128, 0.04566012, 0.23349158, 0.31380357, 0.01295345],
       [0.03160324, 0.01872695, 0.02002924, 0.24228493, 0.68735564],
       [0.07234845, 0.01632043, 0.81568485, 0.09217442, 0.00347185],
       ...,
       [0.72002053, 0.09023495, 0.10439551, 0.06370354, 0.02164547],
       [0.05381132, 0.87540793, 0.00729444, 0.05484594, 0.00864037],
       [0.58280516, 0.23097837, 0.00187719, 0.15886383, 0.02547546]])

## Get Model Evaluation

In [41]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))

[[  35   66   89  125  282]
 [  80  153  181  211  445]
 [ 174  258  371  384  812]
 [ 390  395  561  675 1549]
 [ 899  854 1199 1617 4636]]


In [42]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.02      0.06      0.03       597
           2       0.09      0.14      0.11      1070
           3       0.15      0.19      0.17      1999
           4       0.22      0.19      0.21      3570
           5       0.60      0.50      0.55      9205

    accuracy                           0.36     16441
   macro avg       0.22      0.22      0.21     16441
weighted avg       0.41      0.36      0.38     16441



## Recategories Ratings as Poor (0) and Good(1)

In [49]:
df['Rating'].value_counts()

Rating
0    23486
Name: count, dtype: int64

In [50]:
#RE-Rating as 1,2,3 as 0 and 4,5 as 1
df.replace({'Rating': {1:0,2:0,3:0,4:1,5:1}}, inplace = True)

In [51]:
y=df['Rating']
X=df['Review']

### Train Test split

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,stratify=y,random_state=2529)

In [53]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

### Get Feature Text Conversion to Tokens

In [54]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [55]:
X_train=cv.fit_transform(X_train)
X_test=cv.transform(X_test)

### Get Model Re-Train

In [56]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

### Get Model Prediction

In [58]:
y_pred=model.predict(X_test)
y_pred.shape

(7046,)

In [60]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

### Get Model Evaluation

In [65]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))

[[7046]]


In [64]:
print(confusion_matrix(y_test,y_pred))

[[7046]]


In [63]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7046

    accuracy                           1.00      7046
   macro avg       1.00      1.00      1.00      7046
weighted avg       1.00      1.00      1.00      7046

